### ISSUE TITLE
所有镜像全部无效请快点更新

### ISSUE THREAD

**Issue by weilianbuluo** [Heroic-Studio/Google-Mirrors#11]

**Comment by hmsjy2017** [comment]
经测试，部分链接已失效，但大部分还是能用的。可能与你那边的网络状况有关。

**Comment by weilianbuluo** [comment]
好的，谢谢！












小布丁
***@***.***

广东省机械技师学院
广州市纪律检查委员会职员
15521091376
广东省广州市白云区江高镇江村

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月18日(周六) 凌晨0:23
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Heroic-Studio/Google-Mirrors] 所有镜像全部无效请快点更新 (Issue #11)




 
经测试，部分链接已失效，但大部分还是能用的。可能与你那边的网络状况有关。
