### ISSUE TITLE
维基百科全部镜像已经完全失效了，请更新和完善一下！谢谢！

### ISSUE THREAD

**Issue by weilianbuluo** [Heroic-Studio/Google-Mirrors#14]

**Comment by hmsjy2017** [comment]
已更新。由于本项目的公益性，无法保证SLA。如对稳定性有要求，还是建议自行搭建。

另外请不要重复开启大量issue。如有类似问题，在同一个issue中讨论即可。

**Comment by weilianbuluo** [comment]
好的！那麻烦你了，不好意思喔！












小布丁
***@***.***

广东省机械技师学院
广州市纪律检查委员会职员
15521091376
广东省广州市白云区江高镇江村

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月23日(周四) 凌晨1:23
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Heroic-Studio/Google-Mirrors] 维基百科全部镜像已经完全失效了，请更新和完善一下！谢谢！ (Issue #14)




 
已更新。由于本项目的公益性，无法保证SLA。如对稳定性有要求，还是建议自行搭建。
 
另外请不要重复开启大量issue。如有类似问题，在同一个issue中讨论即可。

**Comment by weilianbuluo** [comment]
你好，你所更新的维基百科镜像每个都打开不了，其它镜像都能打开，偏偏是这个维基百科的镜像打不开，你在哪里复制一个空壳网站过来啊？要是弄不了就下架维基百科镜像网址😓












小布丁
***@***.***

广东省机械技师学院
广州市纪律检查委员会职员
15521091376
广东省广州市白云区江高镇江村

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月23日(周四) 凌晨1:23
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Heroic-Studio/Google-Mirrors] 维基百科全部镜像已经完全失效了，请更新和完善一下！谢谢！ (Issue #14)




 
已更新。由于本项目的公益性，无法保证SLA。如对稳定性有要求，还是建议自行搭建。
 
另外请不要重复开启大量issue。如有类似问题，在同一个issue中讨论即可。

**Comment by hmsjy2017** [comment]
我这边是能正常打开的
![Screenshot_2023-02-24-00-25-31-1](https://user-images.githubusercontent.com/42692274/220968780-a912d870-9b07-4c17-98bc-e45b49e4e1fc.png)

**Comment by weilianbuluo** [comment]
我想我知道是什么原因了！












小布丁
***@***.***

广东省机械技师学院
广州市纪律检查委员会职员
15521091376
广东省广州市白云区江高镇江村

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月24日(周五) 凌晨0:27
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Heroic-Studio/Google-Mirrors] 维基百科全部镜像已经完全失效了，请更新和完善一下！谢谢！ (Issue #14)




 
我这边是能正常打开的
