### ISSUE TITLE
谷歌搜索镜像

### ISSUE THREAD

**Issue by Delvilk** [Heroic-Studio/Google-Mirrors#15]
https://search.vwo50.me/
部署在Dedipath 2C1G的机子上，基于Gin框架，这个配置做反向代理应该足够了吧？🤔
🚀采用Cloudflare CDN ~~加速~~
屏蔽了中国大陆以外的IP以确保稳定性
（能用境外IP访问的也没必要用反代站了吧

**Comment by hmsjy2017** [comment]
反向代理对VPS的配置没有太大要求，这个配置足够了
感谢提供镜像！
