### ISSUE TITLE
Google镜像无法加载

### ISSUE THREAD

**Issue by Ayanaboli** [Heroic-Studio/Google-Mirrors#18]
2023年6月11日访问Google镜像中的[https://s.iit.xyz/](https://s.iit.xyz/)这一链接，发现目前这个链接已失效。
![image](https://github.com/Heroic-Studio/Google-Mirrors/assets/117520566/47586851-3373-4251-8037-f0958c2cb37f)

**Comment by hmsjy2017** [comment]
已更新可用链接
