### ISSUE TITLE
feat: new Google Mirror

### ISSUE THREAD

**Issue by altyl** [Heroic-Studio/Google-Mirrors#22]
[https://rp1.ssh.town/index.php?q=aHR0cHM6Ly93d3cuZ29vZ2xlLmNvbS8_Z3dzX3JkPXNzbA](https://rp1.ssh.town/index.php?q=aHR0cHM6Ly93d3cuZ29vZ2xlLmNvbS8_Z3dzX3JkPXNzbA)

**Comment by hmsjy2017** [comment]
Thanks
