### ISSUE TITLE
鸡场跑路

### ISSUE THREAD

**Issue by helloearthlings** [Heroic-Studio/Google-Mirrors#23]
推荐的鸡场有毒啊 ，才几个月就跑路，能不能靠谱点，带点良心再推广？

**Comment by hmsjy2017** [comment]
没跑路，只是域名被墙了，在联系更新

**Comment by hmsjy2017** [comment]
新域名
https://www.012024.xyz
https://www.022024.xyz
https://www.122023.xyz
https://www.onfly.link
