### ISSUE TITLE
推荐一个新的方式

### ISSUE THREAD

**Issue by chinese-wzq** [Heroic-Studio/Google-Mirrors#3]
[开发者边车（dev-sidecar）](https://github.com/docmirror/dev-sidecar)自带“增强模式”（需通过特殊方式开启），允许通过用户自行搭建免费的clound flare wokers实现流量中转，速度十分可观，但访问谷歌时因ip为公用会出现人机验证。文档链接：[原理说明与搭建](https://github.com/docmirror/dev-sidecar-doc/blob/main/ow.md)末尾的cf-wokers。建议放置在网页末尾作为补充方案。~~谷歌搜索的镜像和v2ray订阅地址真的yyds！~~

**Comment by inkdust-dev** [comment]
你可以自行提交PR来添加此方式。
