### ISSUE TITLE
我这访问下面的加速 大部分都不能访问,能访问的也是碰运气偶尔能,是我本地网络原因么?

### ISSUE THREAD

**Issue by lazeyliu** [Heroic-Studio/Google-Mirrors#30]
谷歌搜索
https://g.luciaz.me/

验证你是否来自浙江大学，三个问题的答案分别是：心灵之约、水朝夕、csxy@123
https://google.speedcloud.icu/

https://gsearch.g.shellten.top/

https://g.savalone.com/

https://rs.http3.lol/index.php?q=aHR0cHM6Ly93d3cuZ29vZ2xlLmNvbS8 （有广告）

**Comment by hmsjy2017** [comment]
一方面是本地网络的原因，另一方面是部分网站失效了
